language: node_js

node_js:
  - '8'

install:
  - npm i -g npm@5

env:
  - TEST_DIR=packages/travix-ui-kit

script:
  - cd $TEST_DIR
  - npm ci
  - npm run ci:lint
  - npm run ci:test

notifications:
  email: false
